# Generated by Django 5.1.4 on 2025-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favcities",
            name="city_name",
            field=models.CharField(default="empty", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
