# Generated by Django 5.1.4 on 2025-04-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherapp", "0002_alter_favcities_city_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favcities",
            name="city_name",
            field=models.CharField(max_length=100),
        ),
    ]
